HostingEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('users/', include('users.urls')),
    path('server/', include('server.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'
urlpatterns = [
    path('', index, name='index'),
    path('store/', store, name='store'),
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/', remove_from_cart, name='remove-from-cart'),
    path('checkout/', checkout, name='checkout'),
    path('cart/', cart, name='cart'),
    path('cashpayment/', cash_payment, name='cash-payment'),
    path('razorpayment/', razorpay_payment, name='razor-payment'),
    path('getAddress/', getAddress, name='get-address')
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('profile/', profile, name='profile'),
    path('profile/orders', profile_orders, name='profile-orders'),
    path('profile/products', profile_products, name='profile-products'),
    path('profile/invoices', invoicelist, name='profile-invoicelist'),
    path('profile/invoices/<str:oid>', GenerateInvoice.as_view(), name='profile-invoice'),
    path('profile/settings', profile_settings, name='profile-settings'),
    path('profile/changeAPIsettings', changeAPISettings, name='change-API')
]

templates/accounts/apisettings.html
{% extends 'accounts/dashboard_base.html' %}
{% block content %}
    <div class="col-10">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary" name="check">Check Connection</button>
        </form>
        {{ result }}
    </div>
{% endblock %}

templates/accounts/dashboard_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{{ title }}</title>
    <style>
        #sidebar {
            padding-bottom: 70vh;
            border-right: lightblue solid 5px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="http://localhost:8000">GitDev</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% url 'shop:index' as index %}
            {% url 'shop:store' as store %}
            <li class="nav-item {% if request.path == index %}active{% endif %}">
                <a class="nav-link" href="{% url 'shop:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == store %}active{% endif %}">
                <a class="nav-link" href="{% url 'shop:store' %}">Store</a>
            </li>

        </ul>
        {% if user.is_authenticated %}

            <ul class="navbar-nav">
                <div class="dropdown mr-3" id='cart'>
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Cart
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% for x in cart.item.all %}
                            <a class="dropdown-item px-1" href="#">{{ x.item.title }} - {{ x.quantity }}</a>
                        {% endfor %}
                        <div class="row d-flex justify-content-center mx-n2 px-0">
                            <div class="col-sm-6">
                                <a class="btn btn-primary" href="{% url 'shop:checkout' %}">Checkout</a>

                            </div>
                            <div class="col-sm-6">
                                <a class="btn btn-primary" href="{% url 'shop:cart' %}">Cart</a>

                            </div>
                        </div>

                    </div>
                </div>
                <li class="nav-item dropdown dropleft">
                    <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'users:profile-orders' %}">Orders</a>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login:login' %}">Login</a>
                </li>
            </ul>

        {% endif %}
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 px-0">
            <nav class="navbar navbar-expand-lg navbar-light bg-light" id="sidebar">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    {% url 'users:profile' as profile %}
                    {% url 'users:profile-orders' as orders1 %}
                    {% url 'users:profile-products' as products %}
                    {% url 'users:profile-invoicelist' as invoices %}
                    {% url 'users:profile-settings' as settings %}
                    {% url 'users:change-API' as apisettings %}
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == profile %}disabled{% endif %}"
                               href="{{ profile }}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == products %}disabled{% endif %}"
                               href="{{ products }}">My Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == orders1 %}disabled{% endif %}"
                               href="{{ orders1 }}">My Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == invoices %}disabled{% endif %}"
                               href="{{ invoices }}">My Invoices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == settings %}disabled{% endif %}"
                               href="{{ settings }}">Settings</a>
                        </li>
                        {% load filters %}
                        {% if request.user|has_group:'admin' or request.user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == apisettings %}disabled{% endif %}"
                                   href="{{ apisettings }}">Change API settings</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        {% block content %}

        {% endblock %}
    </div>

</div>


</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</html>

templates/accounts/profile.html
{% extends 'accounts/dashboard_base.html' %}
{% block content %}
    <div class="col-10">
        <div class="row">
            <div class="col-4">
                <div class="card">
                    <div class="card-title"><h5 class="mt-1" style="text-align: center"><a
                            class="list-group-item" style="border: none; text-decoration: none"
                            href="{% url 'users:profile-settings' %}">
                        My Address</a></h5></div>
                    <div class="card-body">{{ userProfile.fullname }},<br>
                        {{ userProfile.address1 }},<br>
                        {{ userProfile.address2 }},<br>
                        {{ userProfile.pincode }},<br>
                        {{ userProfile.state }},<br>
                        {{ userProfile.country }}.
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-title" style="text-align: center"><a
                            class="list-group-item" style="border: none; text-decoration: none"
                            href="{% url 'users:profile-invoicelist' %}"><h5>My Invoices</h5></a></div>
                    <div class="card-body">
                        <ol>
                            {% for order in orders|dictsortreversed:"placed_date" %}
                                <a href={% url 'users:profile-invoice' order.orderId %}>
                                    <li>Invoice Id - {{ order.orderId }}</li>
                                </a>
                            {% endfor %}
                        </ol>
                        <center>
                            {% if orders.has_previous %}
                                <a href="?page1={{ orders.previous_page_number }}&page2={{ ordersNotDone.number }}">Previous</a>
                            {% endif %}
                            {% if orders.has_next %}
                                <a href="?page1={{ orders.next_page_number }}&page2={{ ordersNotDone.number }}">Next</a>
                            {% endif %}
                        </center>
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-title" style="text-align: center"><a
                            class="list-group-item" style="border: none; text-decoration: none"
                            href="{% url 'users:profile-invoicelist' %}"><h5>Outstanding Payments</h5></a></div>
                    <div class="card-body">
                        <ol>
                            {% for order in ordersNotDone %}
                                <a href="#">
                                    <li>Order - {{ order.orderId }}</li>
                                </a>
                            {% endfor %}
                            <center>
                                {% if ordersNotDone.has_previous %}
                                    <a href="?page2={{ ordersNotDone.previous_page_number }}&page1={{ orders.number }}">Previous</a>
                                {% endif %}
                                {% if ordersNotDone.has_next %}
                                    <a href="?page2={{ ordersNotDone.next_page_number }}&page1={{ orders.number }}">Next</a>
                                {% endif %}
                            </center>
                        </ol>
                    </div>
                </div>
            </div>


        </div>
{% endblock %}

templates/accounts/profile_invoiceslist.html
{% extends 'accounts/dashboard_base.html' %}
{% block content %}
    <div class="col-10">
        <a>
            {% for order in orders|dictsortreversed:"created_date" %}
                <a href="{% url 'users:profile-invoice' order.orderId %}">
                <h4>
                    <li> Order Id - {{ order.orderId }}</li>
                </h4><br>
                </a>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

templates/accounts/profile_orders.html
{% extends 'accounts/dashboard_base.html' %}
{% block content %}
    <div class="col-sm-10">
        <ol>
            {% for order in orders|dictsortreversed:"created_date" %}
                <h3>
                    <li>{% for item in order.cartItems.item.all %}

                        {{ item.item.title }} - {{ item.quantity }}

                    {% endfor %}

                        <a href="{% url 'users:profile-invoice' order.orderId %}"
                           class="btn btn-primary">Invoice</a>
                    </li>
                </h3>
                <br>
                <hr>
            {% endfor %}
        </ol>
    </div>




{% endblock %}

templates/accounts/profile_products.html
{% extends 'accounts/dashboard_base.html' %}


{% block content %}
    <div class="col-10">
        <ol>
            {% for order in orders %}
                {% for item in order.cartItems.item.all %}
                    {% load filters %}
                    {% for num in item.quantity|times %}
                        <h6><li>{{ item.item.title }}</li></h6>
                        <a class="btn btn-primary text-white">Go To Panel</a>

                        <br><hr>
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        </ol>

    </div>
{% endblock %}

templates/accounts/profile_settings.html
{% extends 'accounts/dashboard_base.html' %}
{% block content %}
    <style>
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }
    </style>
    <div class="col-4">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    <div class="col-4">
    <a href="{% url 'account_change_password' %}">Change Password</a>
    </div>
{% endblock %}